[project]
name = "fa-dae2-capstone"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    # Core/runtime
    "python-dotenv>=1.0.1",
    "SQLAlchemy~=2.0",
    # Prefer psycopg v3 (modern driver) with binary wheels
    "psycopg[binary]~=3.2",
    # DataFrame engine: Polars instead of pandas
    "polars>=1.2",
    # Fast DB IO for Polars
    "connectorx>=0.3.5",
    # Optional (kept for later phases; safe to keep installed or add later)
    "snowflake-connector-python~=3.16",
    "cryptography>=42",
    "faker>=25",
]
