version: 2

sources:
  - name: raw
    description: "Raw data tables from Airflow ingestion"
    database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
    schema: "{{ env_var('SNOWFLAKE_SCHEMA') }}"

    tables:
      - name: TRANSACTIONS_STREAMING_KAFKA
        description: "Raw streaming transaction data from Kafka → PostgreSQL pipeline"
        columns:
          - name: tx_id
            description: "Transaction identifier (may have duplicates - handled in staging)"
            tests:
              - not_null
          - name: user_id
            description: "User identifier"
          - name: amount
            description: "Transaction amount"
          - name: currency
            description: "Transaction currency"
          - name: merchant
            description: "Merchant name"
          - name: category
            description: "Transaction category"
          - name: timestamp
            description: "Transaction timestamp"
          - name: ingested_at
            description: "When data was ingested into PostgreSQL"
          - name: airflow_ingested_at
            description: "When Airflow processed the data"

      - name: TRANSACTIONS_BATCH_CSV
        description: "Raw batch transaction data from CSV files"
        columns:
          - name: tx_id
            description: "Transaction identifier (may have duplicates - handled in staging)"
            tests:
              - not_null
          - name: user_id
            description: "User identifier"
          - name: amount
            description: "Transaction amount"
          - name: currency
            description: "Transaction currency"
          - name: merchant
            description: "Merchant name"
          - name: category
            description: "Transaction category"
          - name: timestamp
            description: "Transaction timestamp"
          - name: source_file
            description: "Source CSV filename"
          - name: ingested_at
            description: "When Airflow processed the data"

      - name: USER_REGISTRATIONS
        description: "Raw user profile data from CSV files"
        columns:
          - name: user_id
            description: "Unique identifier for the user"
            tests:
              - not_null
          - name: first_name
            description: "User's first name"
          - name: last_name
            description: "User's last name"
          - name: email
            description: "User's email address"
          - name: age
            description: "User's age in years"
          - name: income_bracket
            description: "User's income bracket category"
          - name: customer_tier
            description: "User's customer tier level"
          - name: risk_profile
            description: "User's risk profile category"
          - name: city
            description: "User's city of residence"
          - name: state
            description: "User's state of residence (abbreviation)"
          - name: country
            description: "User's country of residence"
          - name: registration_date
            description: "Date when user registered"
          - name: preferred_categories
            description: "Comma-separated list of user's preferred transaction categories"
          - name: is_active
            description: "Whether the user account is active"
          - name: source_system
            description: "Source system identifier"
