name: PR CI - SQLFluff Linting

on:
  pull_request:
    branches: [main, develop]
    paths:
      - "**.sql"
      - "dbt_sf/**"
      - ".github/workflows/pr_ci.yml"

jobs:
  PR_CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          version: "latest"

      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: |
            .venv
            .uv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install CI dependencies
        run: |
          uv sync --group ci

      - name: Setup Snowflake Private Key
        run: |
          mkdir -p .secret
          echo "${{ secrets.SNOWFLAKE_PRIVATE_KEY_FILE }}" > ${{ github.workspace }}/.secret/SF_T0.p8

      - name: Run SQLFluff lint
        run: |
          pwd
          uv run dbt debug
          uv run dbt deps
          uv run sqlfluff lint
        env:
          SNOWFLAKE_ACCOUNT: ${{ vars.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ vars.SNOWFLAKE_USER }}
          SNOWFLAKE_DATABASE: ${{ vars.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_WAREHOUSE: ${{ vars.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_ROLE: ${{ vars.SNOWFLAKE_ROLE }}
          SNOWFLAKE_SCHEMA: ${{ vars.SNOWFLAKE_SCHEMA }}
          # Put full path to the private key file due to github actions runner folder structure
          SNOWFLAKE_PRIVATE_KEY_FILE_PATH: ${{ github.workspace }}/.secret/SF_T0.p8
          SNOWFLAKE_PRIVATE_KEY_FILE_PWD: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_FILE_PWD }}
          DBT_PROFILES_DIR: ${{ vars.DBT_PROFILES_DIR }}
          DBT_PROJECT_DIR: ${{ vars.DBT_PROJECT_DIR }}
